//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""729a4bfc-b084-4021-bb97-11c8cb679545"",
            ""actions"": [
                {
                    ""name"": ""MOVEMENT"",
                    ""type"": ""Value"",
                    ""id"": ""901ecc6f-a56a-4f1a-87c8-278d36610019"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JUMP"",
                    ""type"": ""Button"",
                    ""id"": ""7ce197a3-d9dd-4693-900f-cb782005395e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.3)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DASH"",
                    ""type"": ""Button"",
                    ""id"": ""94377685-43dc-4d7e-8ef4-9b58d61cd945"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MENU"",
                    ""type"": ""Button"",
                    ""id"": ""9e9620d9-fa1b-4f41-bc02-717ccc9e3f9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ATTACK"",
                    ""type"": ""Button"",
                    ""id"": ""2b618515-c0cc-42d8-8021-42b6946e03e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SPECIAL"",
                    ""type"": ""Button"",
                    ""id"": ""36100f35-baba-46a6-a0a9-16c4678cbca7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SWITCH"",
                    ""type"": ""Button"",
                    ""id"": ""6a3f0b0d-a7bb-478f-aacc-62a2cfdef2eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""1939f795-f8b0-4abc-b715-bbccae0ca6df"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7f55327d-fcdb-4eb7-a4df-9d757cb28fc6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27d5e544-ee14-47ea-918a-4b090793f8c3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e49c7d72-87a3-4a7a-ae3a-5026d29df3b1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a689cd9d-4bcd-4f52-8c94-7e962b3ae4d8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""565cb5dd-756f-4547-adea-c1603116d5de"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d21b675b-5225-4aea-94cf-34626bf59fd2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6560b9f7-3d2a-40ca-b9e9-e42b711af752"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd4b7e2f-2271-499a-a405-b69e5ebc049a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a5e92751-cab2-4f60-92a3-2811238c279c"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MOVEMENT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f99c6b88-e590-42e3-b83e-a25a93394c24"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34e4c21e-9039-4940-af65-fb96e13ba786"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecde14d7-802e-4f26-8227-bfc46919f21e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""DASH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f67523c-794d-4b5e-948b-f0064fcd5779"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""DASH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""206bfe6a-01cd-4fea-81e4-22de085bdcb9"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MENU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91e0e55c-f14a-485f-a4c0-486476b862f2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MENU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e61149d5-dfe4-4adc-a86d-9e03fdee4aaf"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""ATTACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""734dc928-3f92-4b66-8a4a-cf172c9653fd"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""ATTACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58e014a7-9c0d-496b-b057-6d88e02a9eef"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""SPECIAL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c53a10b5-f3cc-418e-9ea4-844275396a9c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""SPECIAL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b0341c-e611-4549-b644-b86bc52d776f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""SWITCH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""355de419-a2ef-4579-8477-b846d37cbad6"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""SWITCH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuControls"",
            ""id"": ""82612e24-7d61-40d1-9156-6424fb6474e3"",
            ""actions"": [
                {
                    ""name"": ""MENU"",
                    ""type"": ""Button"",
                    ""id"": ""c3cfdf79-c277-45de-96c5-165fc0755e11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BACK"",
                    ""type"": ""Button"",
                    ""id"": ""0d4e4fa9-0a98-48a0-94ba-5d5368e9a803"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NEXT"",
                    ""type"": ""Button"",
                    ""id"": ""05d7860b-6b25-4e2f-b4a0-1dffc56b20b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CHOOSE"",
                    ""type"": ""Button"",
                    ""id"": ""97d75cec-f0db-463b-b58d-15f67ea9b9cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""722a60b9-cc41-4c9c-a2ca-6e64c5472f08"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MENU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78a11401-8cb9-4fde-94b9-db52c533cb9c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MENU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8f664b7-bf12-4954-8ab2-d90628bab97d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""MENU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9a9ec52-567a-4b00-bd62-60a4701be2e8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""CHOOSE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0a33e36-2325-4853-82ae-a01d1ca7098b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""CHOOSE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3980a72e-57b5-4031-a94b-4371ff74a5c0"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""CHOOSE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c5e32fc-108d-472a-864d-2c004dadabc2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea26803b-ae24-42d7-b5f4-0531bb679f43"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44bb20d1-a6a3-4cc0-8320-7bff7b8ec499"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63610bfc-e1bb-4172-8a8c-10c1d0d27b1e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""190d5be5-0c8c-43a1-862d-3997080503d7"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad396b61-20cd-4912-8d9e-c4677d68e3e8"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c8ecd5-4cef-43a3-964c-26b86b191792"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""312c54d3-c6fa-4f35-9983-f56b1d3aeb82"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d454dc61-00db-4b42-893e-c8ada8d38f2c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78ac246b-c6e9-4a6c-9de9-b6c01036c23f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""420dfe4b-2f23-464f-886c-52e374873000"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e099d9fa-8048-4331-b490-2dcbf6a3fb4f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control Scheme"",
                    ""action"": ""NEXT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Control Scheme"",
            ""bindingGroup"": ""Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_MOVEMENT = m_Gameplay.FindAction("MOVEMENT", throwIfNotFound: true);
        m_Gameplay_JUMP = m_Gameplay.FindAction("JUMP", throwIfNotFound: true);
        m_Gameplay_DASH = m_Gameplay.FindAction("DASH", throwIfNotFound: true);
        m_Gameplay_MENU = m_Gameplay.FindAction("MENU", throwIfNotFound: true);
        m_Gameplay_ATTACK = m_Gameplay.FindAction("ATTACK", throwIfNotFound: true);
        m_Gameplay_SPECIAL = m_Gameplay.FindAction("SPECIAL", throwIfNotFound: true);
        m_Gameplay_SWITCH = m_Gameplay.FindAction("SWITCH", throwIfNotFound: true);
        // MenuControls
        m_MenuControls = asset.FindActionMap("MenuControls", throwIfNotFound: true);
        m_MenuControls_MENU = m_MenuControls.FindAction("MENU", throwIfNotFound: true);
        m_MenuControls_BACK = m_MenuControls.FindAction("BACK", throwIfNotFound: true);
        m_MenuControls_NEXT = m_MenuControls.FindAction("NEXT", throwIfNotFound: true);
        m_MenuControls_CHOOSE = m_MenuControls.FindAction("CHOOSE", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_MOVEMENT;
    private readonly InputAction m_Gameplay_JUMP;
    private readonly InputAction m_Gameplay_DASH;
    private readonly InputAction m_Gameplay_MENU;
    private readonly InputAction m_Gameplay_ATTACK;
    private readonly InputAction m_Gameplay_SPECIAL;
    private readonly InputAction m_Gameplay_SWITCH;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MOVEMENT => m_Wrapper.m_Gameplay_MOVEMENT;
        public InputAction @JUMP => m_Wrapper.m_Gameplay_JUMP;
        public InputAction @DASH => m_Wrapper.m_Gameplay_DASH;
        public InputAction @MENU => m_Wrapper.m_Gameplay_MENU;
        public InputAction @ATTACK => m_Wrapper.m_Gameplay_ATTACK;
        public InputAction @SPECIAL => m_Wrapper.m_Gameplay_SPECIAL;
        public InputAction @SWITCH => m_Wrapper.m_Gameplay_SWITCH;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @MOVEMENT.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMOVEMENT;
                @MOVEMENT.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMOVEMENT;
                @MOVEMENT.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMOVEMENT;
                @JUMP.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJUMP;
                @JUMP.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJUMP;
                @JUMP.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJUMP;
                @DASH.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDASH;
                @DASH.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDASH;
                @DASH.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDASH;
                @MENU.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMENU;
                @MENU.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMENU;
                @MENU.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMENU;
                @ATTACK.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnATTACK;
                @ATTACK.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnATTACK;
                @ATTACK.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnATTACK;
                @SPECIAL.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSPECIAL;
                @SPECIAL.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSPECIAL;
                @SPECIAL.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSPECIAL;
                @SWITCH.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSWITCH;
                @SWITCH.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSWITCH;
                @SWITCH.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSWITCH;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MOVEMENT.started += instance.OnMOVEMENT;
                @MOVEMENT.performed += instance.OnMOVEMENT;
                @MOVEMENT.canceled += instance.OnMOVEMENT;
                @JUMP.started += instance.OnJUMP;
                @JUMP.performed += instance.OnJUMP;
                @JUMP.canceled += instance.OnJUMP;
                @DASH.started += instance.OnDASH;
                @DASH.performed += instance.OnDASH;
                @DASH.canceled += instance.OnDASH;
                @MENU.started += instance.OnMENU;
                @MENU.performed += instance.OnMENU;
                @MENU.canceled += instance.OnMENU;
                @ATTACK.started += instance.OnATTACK;
                @ATTACK.performed += instance.OnATTACK;
                @ATTACK.canceled += instance.OnATTACK;
                @SPECIAL.started += instance.OnSPECIAL;
                @SPECIAL.performed += instance.OnSPECIAL;
                @SPECIAL.canceled += instance.OnSPECIAL;
                @SWITCH.started += instance.OnSWITCH;
                @SWITCH.performed += instance.OnSWITCH;
                @SWITCH.canceled += instance.OnSWITCH;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // MenuControls
    private readonly InputActionMap m_MenuControls;
    private IMenuControlsActions m_MenuControlsActionsCallbackInterface;
    private readonly InputAction m_MenuControls_MENU;
    private readonly InputAction m_MenuControls_BACK;
    private readonly InputAction m_MenuControls_NEXT;
    private readonly InputAction m_MenuControls_CHOOSE;
    public struct MenuControlsActions
    {
        private @PlayerControls m_Wrapper;
        public MenuControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MENU => m_Wrapper.m_MenuControls_MENU;
        public InputAction @BACK => m_Wrapper.m_MenuControls_BACK;
        public InputAction @NEXT => m_Wrapper.m_MenuControls_NEXT;
        public InputAction @CHOOSE => m_Wrapper.m_MenuControls_CHOOSE;
        public InputActionMap Get() { return m_Wrapper.m_MenuControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuControlsActions set) { return set.Get(); }
        public void SetCallbacks(IMenuControlsActions instance)
        {
            if (m_Wrapper.m_MenuControlsActionsCallbackInterface != null)
            {
                @MENU.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMENU;
                @MENU.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMENU;
                @MENU.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMENU;
                @BACK.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnBACK;
                @BACK.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnBACK;
                @BACK.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnBACK;
                @NEXT.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnNEXT;
                @NEXT.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnNEXT;
                @NEXT.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnNEXT;
                @CHOOSE.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnCHOOSE;
                @CHOOSE.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnCHOOSE;
                @CHOOSE.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnCHOOSE;
            }
            m_Wrapper.m_MenuControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MENU.started += instance.OnMENU;
                @MENU.performed += instance.OnMENU;
                @MENU.canceled += instance.OnMENU;
                @BACK.started += instance.OnBACK;
                @BACK.performed += instance.OnBACK;
                @BACK.canceled += instance.OnBACK;
                @NEXT.started += instance.OnNEXT;
                @NEXT.performed += instance.OnNEXT;
                @NEXT.canceled += instance.OnNEXT;
                @CHOOSE.started += instance.OnCHOOSE;
                @CHOOSE.performed += instance.OnCHOOSE;
                @CHOOSE.canceled += instance.OnCHOOSE;
            }
        }
    }
    public MenuControlsActions @MenuControls => new MenuControlsActions(this);
    private int m_ControlSchemeSchemeIndex = -1;
    public InputControlScheme ControlSchemeScheme
    {
        get
        {
            if (m_ControlSchemeSchemeIndex == -1) m_ControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Control Scheme");
            return asset.controlSchemes[m_ControlSchemeSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnMOVEMENT(InputAction.CallbackContext context);
        void OnJUMP(InputAction.CallbackContext context);
        void OnDASH(InputAction.CallbackContext context);
        void OnMENU(InputAction.CallbackContext context);
        void OnATTACK(InputAction.CallbackContext context);
        void OnSPECIAL(InputAction.CallbackContext context);
        void OnSWITCH(InputAction.CallbackContext context);
    }
    public interface IMenuControlsActions
    {
        void OnMENU(InputAction.CallbackContext context);
        void OnBACK(InputAction.CallbackContext context);
        void OnNEXT(InputAction.CallbackContext context);
        void OnCHOOSE(InputAction.CallbackContext context);
    }
}
